const cities = [
    { name: "New York", zone: "America/New_York" }, { name: "Los Angeles", zone: "America/Los_Angeles" }, { name: "Chicago", zone: "America/Chicago" },
    { name: "Denver", zone: "America/Denver" }, { name: "Miami", zone: "America/New_York" }, { name: "Seattle", zone: "America/Los_Angeles" },
    { name: "Boston", zone: "America/New_York" }, { name: "San Francisco", zone: "America/Los_Angeles" }, { name: "Atlanta", zone: "America/New_York" },
    { name: "Dallas", zone: "America/Chicago" }, { name: "Houston", zone: "America/Chicago" }, { name: "Phoenix", zone: "America/Phoenix" },
    { name: "Detroit", zone: "America/Detroit" }, { name: "Minneapolis", zone: "America/Chicago" }, { name: "Philadelphia", zone: "America/New_York" },
    { name: "San Diego", zone: "America/Los_Angeles" }, { name: "Tampa", zone: "America/New_York" }, { name: "St. Louis", zone: "America/Chicago" },
    { name: "Baltimore", zone: "America/New_York" }, { name: "Charlotte", zone: "America/New_York" }, { name: "Orlando", zone: "America/New_York" },
    { name: "Portland", zone: "America/Los_Angeles" }, { name: "San Antonio", zone: "America/Chicago" }, { name: "Pittsburgh", zone: "America/New_York" },
    { name: "Cincinnati", zone: "America/New_York" }, { name: "Las Vegas", zone: "America/Los_Angeles" }, { name: "Kansas City", zone: "America/Chicago" },
    { name: "Cleveland", zone: "America/New_York" }, { name: "Columbus", zone: "America/New_York" }, { name: "Indianapolis", zone: "America/Indiana/Indianapolis" },
    { name: "Toronto", zone: "America/Toronto" }, { name: "Montreal", zone: "America/Toronto" }, { name: "Vancouver", zone: "America/Vancouver" },
    { name: "Calgary", zone: "America/Edmonton" }, { name: "Ottawa", zone: "America/Toronto" }, { name: "Edmonton", zone: "America/Edmonton" },
    { name: "Winnipeg", zone: "America/Winnipeg" }, { name: "Quebec City", zone: "America/Toronto" }, { name: "Hamilton", zone: "America/Toronto" },
    { name: "Halifax", zone: "America/Halifax" },
    { name: "Belgrade", zone: "Europe/Belgrade" },
    { name: "Zagreb", zone: "Europe/Zagreb" },
    { name: "Sarajevo", zone: "Europe/Sarajevo" },
    { name: "Podgorica", zone: "Europe/Podgorica" },
    { name: "Skopje", zone: "Europe/Skopje" },
    { name: "Tirana", zone: "Europe/Tirane" },
    { name: "Sofia", zone: "Europe/Sofia" },
    { name: "Ljubljana", zone: "Europe/Ljubljana" },
    { name: "Pristina", zone: "Europe/Belgrade" },
    { name: "London", zone: "Europe/London" }, { name: "Manchester", zone: "Europe/London" },
    { name: "Birmingham", zone: "Europe/London" }, { name: "Glasgow", zone: "Europe/London" }, { name: "Liverpool", zone: "Europe/London" },
    { name: "Edinburgh", zone: "Europe/London" }, { name: "Leeds", zone: "Europe/London" }, { name: "Bristol", zone: "Europe/London" },
    { name: "Dublin", zone: "Europe/Dublin" }, { name: "Cork", zone: "Europe/Dublin" }, { name: "Paris", zone: "Europe/Paris" },
    { name: "Lyon", zone: "Europe/Paris" }, { name: "Marseille", zone: "Europe/Paris" }, { name: "Toulouse", zone: "Europe/Paris" },
    { name: "Nice", zone: "Europe/Paris" }, { name: "Nantes", zone: "Europe/Paris" }, { name: "Strasbourg", zone: "Europe/Paris" },
    { name: "Montpellier", zone: "Europe/Paris" }, { name: "Bordeaux", zone: "Europe/Paris" }, { name: "Lille", zone: "Europe/Paris" },
    { name: "Berlin", zone: "Europe/Berlin" }, { name: "Munich", zone: "Europe/Berlin" }, { name: "Hamburg", zone: "Europe/Berlin" },
    { name: "Frankfurt", zone: "Europe/Berlin" }, { name: "Cologne", zone: "Europe/Berlin" }, { name: "Stuttgart", zone: "Europe/Berlin" },
    { name: "Düsseldorf", zone: "Europe/Berlin" }, { name: "Dortmund", zone: "Europe/Berlin" }, { name: "Essen", zone: "Europe/Berlin" },
    { name: "Leipzig", zone: "Europe/Berlin" }, { name: "Rome", zone: "Europe/Rome" }, { name: "Milan", zone: "Europe/Rome" },
    { name: "Naples", zone: "Europe/Rome" }, { name: "Turin", zone: "Europe/Rome" }, { name: "Florence", zone: "Europe/Rome" },
    { name: "Bologna", zone: "Europe/Rome" }, { name: "Genoa", zone: "Europe/Rome" }, { name: "Venice", zone: "Europe/Rome" },
    { name: "Madrid", zone: "Europe/Madrid" }, { name: "Barcelona", zone: "Europe/Madrid" }, { name: "Valencia", zone: "Europe/Madrid" },
    { name: "Seville", zone: "Europe/Madrid" }, { name: "Zaragoza", zone: "Europe/Madrid" }, { name: "Málaga", zone: "Europe/Madrid" },
    { name: "Bilbao", zone: "Europe/Madrid" }, { name: "Amsterdam", zone: "Europe/Amsterdam" }, { name: "Rotterdam", zone: "Europe/Amsterdam" },
    { name: "The Hague", zone: "Europe/Amsterdam" }, { name: "Utrecht", zone: "Europe/Amsterdam" }, { name: "Brussels", zone: "Europe/Brussels" },
    { name: "Antwerp", zone: "Europe/Brussels" }, { name: "Ghent", zone: "Europe/Brussels" }, { name: "Vienna", zone: "Europe/Vienna" },
    { name: "Zurich", zone: "Europe/Zurich" }, { name: "Geneva", zone: "Europe/Zurich" }, { name: "Basel", zone: "Europe/Zurich" },
    { name: "Prague", zone: "Europe/Prague" }, { name: "Warsaw", zone: "Europe/Warsaw" }, { name: "Budapest", zone: "Europe/Budapest" },
    { name: "Bucharest", zone: "Europe/Bucharest" }, { name: "Athens", zone: "Europe/Athens" }, { name: "Lisbon", zone: "Europe/Lisbon" },
    { name: "Moscow", zone: "Europe/Moscow" }, { name: "St. Petersburg", zone: "Europe/Moscow" }, { name: "Istanbul", zone: "Europe/Istanbul" },
    { name: "Ankara", zone: "Europe/Istanbul" }, { name: "Tokyo", zone: "Asia/Tokyo" }, { name: "Osaka", zone: "Asia/Tokyo" },
    { name: "Kyoto", zone: "Asia/Tokyo" }, { name: "Yokohama", zone: "Asia/Tokyo" }, { name: "Nagoya", zone: "Asia/Tokyo" },
    { name: "Sapporo", zone: "Asia/Tokyo" }, { name: "Fukuoka", zone: "Asia/Tokyo" }, { name: "Kobe", zone: "Asia/Tokyo" },
    { name: "Seoul", zone: "Asia/Seoul" }, { name: "Busan", zone: "Asia/Seoul" }, { name: "Incheon", zone: "Asia/Seoul" },
    { name: "Beijing", zone: "Asia/Shanghai" }, { name: "Shanghai", zone: "Asia/Shanghai" }, { name: "Guangzhou", zone: "Asia/Shanghai" },
    { name: "Shenzhen", zone: "Asia/Shanghai" }, { name: "Chengdu", zone: "Asia/Shanghai" }, { name: "Chongqing", zone: "Asia/Shanghai" },
    { name: "Tianjin", zone: "Asia/Shanghai" }, { name: "Wuhan", zone: "Asia/Shanghai" }, { name: "Xi'an", zone: "Asia/Shanghai" },
    { name: "Hangzhou", zone: "Asia/Shanghai" }, { name: "Hong Kong", zone: "Asia/Hong_Kong" }, { name: "Singapore", zone: "Asia/Singapore" },
    { name: "Bangkok", zone: "Asia/Bangkok" }, { name: "Kuala Lumpur", zone: "Asia/Kuala_Lumpur" }, { name: "Jakarta", zone: "Asia/Jakarta" },
    { name: "Manila", zone: "Asia/Manila" }, { name: "Ho Chi Minh City", zone: "Asia/Ho_Chi_Minh" }, { name: "Hanoi", zone: "Asia/Ho_Chi_Minh" },
    { name: "Yangon", zone: "Asia/Yangon" }, { name: "Phnom Penh", zone: "Asia/Phnom_Penh" }, { name: "Vientiane", zone: "Asia/Vientiane" },
    { name: "Mumbai", zone: "Asia/Kolkata" }, { name: "Delhi", zone: "Asia/Kolkata" }, { name: "Bangalore", zone: "Asia/Kolkata" },
    { name: "Chennai", zone: "Asia/Kolkata" }, { name: "Kolkata", zone: "Asia/Kolkata" }, { name: "Hyderabad", zone: "Asia/Kolkata" },
    { name: "Pune", zone: "Asia/Kolkata" }, { name: "Ahmedabad", zone: "Asia/Kolkata" }, { name: "Jaipur", zone: "Asia/Kolkata" },
    { name: "Surat", zone: "Asia/Kolkata" }, { name: "Karachi", zone: "Asia/Karachi" }, { name: "Lahore", zone: "Asia/Karachi" },
    { name: "Islamabad", zone: "Asia/Karachi" }, { name: "Dhaka", zone: "Asia/Dhaka" }, { name: "Colombo", zone: "Asia/Colombo" },
    { name: "Kathmandu", zone: "Asia/Kathmandu" }, { name: "Dubai", zone: "Asia/Dubai" }, { name: "Abu Dhabi", zone: "Asia/Dubai" },
    { name: "Riyadh", zone: "Asia/Riyadh" }, { name: "Jeddah", zone: "Asia/Riyadh" }, { name: "Doha", zone: "Asia/Qatar" },
    { name: "Kuwait City", zone: "Asia/Kuwait" }, { name: "Manama", zone: "Asia/Bahrain" }, { name: "Muscat", zone: "Asia/Muscat" },
    { name: "Tehran", zone: "Asia/Tehran" }, { name: "Baghdad", zone: "Asia/Baghdad" }, { name: "Amman", zone: "Asia/Amman" },
    { name: "Beirut", zone: "Asia/Beirut" }, { name: "Damascus", zone: "Asia/Damascus" }, { name: "Jerusalem", zone: "Asia/Jerusalem" },
    { name: "Tel Aviv", zone: "Asia/Jerusalem" }, { name: "Sydney", zone: "Australia/Sydney" }, { name: "Melbourne", zone: "Australia/Melbourne" },
    { name: "Brisbane", zone: "Australia/Brisbane" }, { name: "Perth", zone: "Australia/Perth" }, { name: "Adelaide", zone: "Australia/Adelaide" },
    { name: "Canberra", zone: "Australia/Sydney" }, { name: "Gold Coast", zone: "Australia/Brisbane" }, { name: "Newcastle", zone: "Australia/Sydney" },
    { name: "Auckland", zone: "Pacific/Auckland" }, { name: "Wellington", zone: "Pacific/Auckland" }, { name: "Christchurch", zone: "Pacific/Auckland" },
    { name: "São Paulo", zone: "America/Sao_Paulo" }, { name: "Rio de Janeiro", zone: "America/Sao_Paulo" }, { name: "Brasília", zone: "America/Sao_Paulo" },
    { name: "Salvador", zone: "America/Bahia" }, { name: "Fortaleza", zone: "America/Fortaleza" }, { name: "Belo Horizonte", zone: "America/Sao_Paulo" },
    { name: "Manaus", zone: "America/Manaus" }, { name: "Curitiba", zone: "America/Sao_Paulo" }, { name: "Recife", zone: "America/Recife" },
    { name: "Porto Alegre", zone: "America/Sao_Paulo" }, { name: "Buenos Aires", zone: "America/Argentina/Buenos_Aires" }, { name: "Córdoba", zone: "America/Argentina/Cordoba" },
    { name: "Rosario", zone: "America/Argentina/Cordoba" }, { name: "Mendoza", zone: "America/Argentina/Mendoza" }, { name: "Santiago", zone: "America/Santiago" },
    { name: "Lima", zone: "America/Lima" }, { name: "Bogotá", zone: "America/Bogota" }, { name: "Caracas", zone: "America/Caracas" },
    { name: "Quito", zone: "America/Guayaquil" }, { name: "La Paz", zone: "America/La_Paz" }, { name: "Montevideo", zone: "America/Montevideo" },
    { name: "Asunción", zone: "America/Asuncion" }, { name: "Mexico City", zone: "America/Mexico_City" }, { name: "Guadalajara", zone: "America/Mexico_City" },
    { name: "Monterrey", zone: "America/Monterrey" }, { name: "Puebla", zone: "America/Mexico_City" }, { name: "Tijuana", zone: "America/Tijuana" },
    { name: "León", zone: "America/Mexico_City" }, { name: "Cairo", zone: "Africa/Cairo" }, { name: "Alexandria", zone: "Africa/Cairo" },
    { name: "Lagos", zone: "Africa/Lagos" }, { name: "Nairobi", zone: "Africa/Nairobi" }, { name: "Johannesburg", zone: "Africa/Johannesburg" },
    { name: "Cape Town", zone: "Africa/Johannesburg" }, { name: "Casablanca", zone: "Africa/Casablanca" }, { name: "Accra", zone: "Africa/Accra" },
    { name: "Addis Ababa", zone: "Africa/Addis_Ababa" }, { name: "Dar es Salaam", zone: "Africa/Dar_es_Salaam" }
];
